server:
  port: 8080
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

logging:
  level:
    root: INFO
    DNAnalyzer: DEBUG
    org.springframework.web: DEBUG

analysis:
  temp-dir: ${java.io.tmpdir}/dnanalyzer
  max-sequence-length: 10000000
