name: Tweet on new release

on:
  release:
    types: [published]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Craft tweet text
        id: compose
        run: |
          echo "TWEET=🚀 DNAnalyzer ${{ github.event.release.tag_name }} shipped. Private on-device DNA insights just improved. Notes ➜ ${{ github.event.release.html_url }}" >> $GITHUB_ENV
      - name: Send tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ env.TWEET }}
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
